# Generated by Django 5.1.2 on 2024-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('titre', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
    ]
